name: deploy-prod

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - backend/cdk/**
      - bin/**
      - public/**
      - src/**
      - index.html
      - LICENSE
      - package-lock.json
      - package.json
      - README.md
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    outputs:
      PREFIX: ${{ steps.output-step.outputs.PREFIX }}
      DOMAIN_NAME_DISTRIBUTION: ${{ steps.output-step.outputs.DOMAIN_NAME_DISTRIBUTION }}
      CLOUDFRONT_DISTRIBUTION: ${{ steps.output-step.outputs.CLOUDFRONT_DISTRIBUTION }}
      BUCKET_DISTRIBUTION: ${{ steps.output-step.outputs.BUCKET_DISTRIBUTION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: CDK Deploy
        working-directory: backend/cdk
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          cdk deploy --all --require-approval never --outputs-file cdk-outputs.json

      - name: Extract Outputs
        id: output-step
        working-directory: backend/cdk
        run: |
          STACK_NAME_US=$(jq -r 'keys[0]' cdk-outputs.json)
          PREFIX=$(jq -r --arg STACK_NAME_US "$STACK_NAME_US" '.[$STACK_NAME_US].Prefix' cdk-outputs.json)
          CLOUDFRONT_DISTRIBUTION=$(jq -r --arg STACK_NAME_US "$STACK_NAME_US" '.[$STACK_NAME_US].CloudfrontDistribution' cdk-outputs.json)
          BUCKET_DISTRIBUTION=$(jq -r --arg STACK_NAME_US "$STACK_NAME_US" '.[$STACK_NAME_US].BucketDistribution' cdk-outputs.json)
          DOMAIN_NAME_DISTRIBUTION=$(jq -r --arg STACK_NAME_US "$STACK_NAME_US" '.[$STACK_NAME_US].DomainNameDistribution' cdk-outputs.json)
          echo "PREFIX=${PREFIX}" >> $GITHUB_OUTPUT
          echo "CLOUDFRONT_DISTRIBUTION=${CLOUDFRONT_DISTRIBUTION}" >> $GITHUB_OUTPUT
          echo "BUCKET_DISTRIBUTION=${BUCKET_DISTRIBUTION}" >> $GITHUB_OUTPUT
          echo "DOMAIN_NAME_DISTRIBUTION=${DOMAIN_NAME_DISTRIBUTION}" >> $GITHUB_OUTPUT

  deploy-node:
    runs-on: ubuntu-latest
    needs:
      - deploy-cdk
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Write CDK outputs to .env.production
        run: |
          sed -i 's/^VITE_DISTRIBUTION_DOMAIN_NAME=.*/VITE_DISTRIBUTION_DOMAIN_NAME=${{ needs.deploy-cdk.outputs.DOMAIN_NAME_DISTRIBUTION }}/' .env.production

      - name: Log .env.production changes
        run: |
          echo "Updated .env.production:"
          cat .env.production

      - name: npm ci, build
        run: |
          npm ci
          npm run build --if-present

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Sync /img with S3 (Cache-Control)
        run: |
          aws s3 sync dist/img s3://${{ needs.deploy-cdk.outputs.BUCKET_DISTRIBUTION }}/img \
            --follow-symlinks \
            --delete \
            --cache-control "max-age=31536000"
      - name: Sync /assets with S3 (Cache-Control)
        run: |
          aws s3 sync dist/assets s3://${{ needs.deploy-cdk.outputs.BUCKET_DISTRIBUTION }}/assets \
            --follow-symlinks \
            --delete \
            --cache-control "max-age=31536000"
      - name: Sync other files with S3 (No Cache-Control)
        run: |
          aws s3 sync dist s3://${{ needs.deploy-cdk.outputs.BUCKET_DISTRIBUTION }} \
            --exclude "img/*" \
            --exclude "assets/*" \
            --follow-symlinks \
            --delete

      - name: Invalidate CloudFront
        uses: badsyntax/github-action-aws-cloudfront@master
        with:
          distribution-id: ${{  needs.deploy-cdk.outputs.CLOUDFRONT_DISTRIBUTION }}
          aws-region: ap-northeast-1
          invalidate-paths: "/*"
          default-root-object: "index.html"
          include-origin-prefix: false
